# Dependabot configuration for SAGE
# Automated dependency updates

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sage-x-project/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sage-x-project/maintainers"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # npm (Smart Contracts)
  - package-ecosystem: "npm"
    directory: "/contracts/ethereum"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - "sage-x-project/maintainers"
    labels:
      - "dependencies"
      - "contracts"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sage-x-project/maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
