version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - path: ".*\\.gen\\.go"
        linters:
          - govet
          - errcheck
          - staticcheck
          - ineffassign
      - path: "contracts/ethereum/bindings/go/"
        text: "local import"
