version: "2"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
