version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
  # Note: gofmt/gofumpt are formatters in v2, use 'make fmt' instead

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - .git
  exclude-files:
    - contracts/ethereum/bindings/go/example.go
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: ".*\\.gen\\.go"
      linters:
        - govet
        - errcheck
        - staticcheck
        - ineffassign
    - path: "contracts/ethereum/bindings/go/"
      text: "local import"
