version: "2"

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules
    - .git
  skip-files:
    - contracts/ethereum/bindings/go/example.go

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
  # Note: gofmt is handled separately as a formatter

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: ".*\\.gen\\.go"
      linters:
        - govet
        - errcheck
        - staticcheck
        - ineffassign
    - path: "contracts/ethereum/bindings/go/"
      text: "local import"
