name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize SAGE with '...'
        2. Call function '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Agent (HPKE/Session)
        - Crypto (Keys/Signatures)
        - DID (Resolution/Registry)
        - Blockchain (Ethereum/Solana/Kaia)
        - Storage (Memory/PostgreSQL)
        - Health/Metrics
        - CLI Tools
        - Smart Contracts
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go version go1.23.0 darwin/arm64
    validations:
      required: true

  - type: input
    id: sage-version
    attributes:
      label: SAGE Version
      description: Output of `sage-crypto --version` or git commit hash
      placeholder: v1.0.1 or commit hash
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Operating system version
      placeholder: Ubuntu 22.04, macOS 14.5, Windows 11, etc.

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - amd64
        - arm64
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Network configuration
        - Blockchain node details
        - Database configuration
        - etc.

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If applicable, paste relevant configuration (remove sensitive data)
      render: yaml
      placeholder: Paste configuration here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information above
          required: true
        - label: I have removed any sensitive information from logs and configuration
          required: true
        - label: I can reproduce this issue consistently
          required: false
