# Grafana Datasource Configuration for Prometheus
# Auto-provisioned datasource for SAGE monitoring

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      httpMethod: "POST"
    version: 1
